exclude:
  - .sass-cache/*
  - .jekyll-cache/*
  - gemfiles/*
  - Gemfile
  - Gemfile.lock
  - node_modules/*
  - vendor/bundle/*
  - vendor/cache/*
  - vendor/gems/*
  - vendor/ruby/*

domain: nikitamamay.github.io
url: https://nikitamamay.github.io
# baseurl: /_site/
source: ./src
destination: ./_site
